In [2]:
import pandas as pd

df = pd.read_csv('/content/rainfall_prediction_with_missing.csv')

In [3]:
df.head()

,id,date,month,location,temp_max_c,temp_min_c,humidity_percent,cloud_cover_percent,wind_speed_kph,pressure_hpa,precip_prev_day_mm,rainfall_mm
0,1,01/01/2023,1.0,Karachi,27.605144,12.167012,NaN,45.326656,19.236382,1002.030229,NaN,22.1
1,2,NaN,1.0,Karachi,28.793970,12.392074,85.987249,76.862808,NaN,1009.833796,0.000000,15.0
2,3,03/01/2023,NaN,Karachi,28.518762,12.837860,38.188092,44.581696,NaN,1000.339472,0.000000,11.7
3,4,04/01/2023,1.0,Karachi,22.823596,19.760699,57.157387,30.957574,9.102446,1020.018718,0.360457,12.9
4,5,NaN,1.0,Karachi,28.572372,14.035231,72.230906,54.082991,NaN,1013.684865,0.000000,22.3

In [5]:
display(df.head())
display(df.info())
display(df.isnull().sum())

,id,date,month,location,temp_max_c,temp_min_c,humidity_percent,cloud_cover_percent,wind_speed_kph,pressure_hpa,precip_prev_day_mm,rainfall_mm
0,1,01/01/2023,1.0,Karachi,27.605144,12.167012,NaN,45.326656,19.236382,1002.030229,NaN,22.1
1,2,NaN,1.0,Karachi,28.793970,12.392074,85.987249,76.862808,NaN,1009.833796,0.000000,15.0
2,3,03/01/2023,NaN,Karachi,28.518762,12.837860,38.188092,44.581696,NaN,1000.339472,0.000000,11.7
3,4,04/01/2023,1.0,Karachi,22.823596,19.760699,57.157387,30.957574,9.102446,1020.018718,0.360457,12.9
4,5,NaN,1.0,Karachi,28.572372,14.035231,72.230906,54.082991,NaN,1013.684865,0.000000,22.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   500 non-null    int64
 1   date                 453 non-null    object
 2   month                467 non-null    float64
 3   location             442 non-null    object
 4   temp_max_c           444 non-null    float64
 5   temp_min_c           455 non-null    float64
 6   humidity_percent     456 non-null    float64
 7   cloud_cover_percent  453 non-null    float64
 8   wind_speed_kph       453 non-null    float64
 9   pressure_hpa         438 non-null    float64
 10  precip_prev_day_mm   441 non-null    float64
 11  rainfall_mm          500 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 47.0+ KB

None

id                      0
date                   47
month                  33
location               58
temp_max_c             56
temp_min_c             45
humidity_percent       44
cloud_cover_percent    47
wind_speed_kph         47
pressure_hpa           62
precip_prev_day_mm     59
rainfall_mm             0
dtype: int64

In [6]:
# Impute numerical columns with the mean
numerical_cols = ['month', 'temp_max_c', 'wind_speed_kph', 'pressure_hpa', 'precip_prev_day_mm', 'cloud_cover_percent']
for col in numerical_cols:
    if col in df.columns:
        df[col] = df[col].fillna(df[col].mean())

# Impute 'location' with the mode
if 'location' in df.columns:
    df['location'] = df['location'].fillna(df['location'].mode()[0])

# Verify that all missing values have been handled
display(df.isnull().sum())

id                      0
date                   47
month                   0
location                0
temp_max_c              0
temp_min_c             45
humidity_percent       44
cloud_cover_percent     0
wind_speed_kph          0
pressure_hpa            0
precip_prev_day_mm      0
rainfall_mm             0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

X = df.drop(['id', 'date', 'rainfall_mm'], axis=1)
y = df['rainfall_mm']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (400, 9)
Shape of X_test: (100, 9)
Shape of y_train: (400,)
Shape of y_test: (100,)